In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
data = np.random.randint(0,100,(10,2))

In [5]:
data

array([[42, 30],
       [69,  9],
       [46, 80],
       [11, 91],
       [18, 45],
       [65, 12],
       [33, 94],
       [62, 90],
       [73, 88],
       [64, 22]])

In [6]:
sm = MinMaxScaler()

In [7]:
sm.fit(data)

/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
sm.transform(data)

array([[ 0.5       ,  0.24705882],
       [ 0.93548387,  0.        ],
       [ 0.56451613,  0.83529412],
       [ 0.        ,  0.96470588],
       [ 0.11290323,  0.42352941],
       [ 0.87096774,  0.03529412],
       [ 0.35483871,  1.        ],
       [ 0.82258065,  0.95294118],
       [ 1.        ,  0.92941176],
       [ 0.85483871,  0.15294118]])

In [9]:
sm.fit_transform(data)

/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.5       ,  0.24705882],
       [ 0.93548387,  0.        ],
       [ 0.56451613,  0.83529412],
       [ 0.        ,  0.96470588],
       [ 0.11290323,  0.42352941],
       [ 0.87096774,  0.03529412],
       [ 0.35483871,  1.        ],
       [ 0.82258065,  0.95294118],
       [ 1.        ,  0.92941176],
       [ 0.85483871,  0.15294118]])

In [10]:
import pandas as pd


In [15]:
df = pd.DataFrame(data = np.random.randint(0,101,(50,4)), columns = ['f1','f2','f3','label'])

In [17]:
df

f1   f2   f3  label
0   84   29   55     32
1   47    6   81     63
2   18   44   23     48
3   48   74   67     38
4   60   14   47     12
5   56   83   34     70
6   98   63   45     25
7   17   51   80     26
8   87    2   70     39
9   95   52   33     38
10  37   42   43     18
11  10   42   19     52
12  29   31   24     32
13  35   24   23     36
14  89   31   51     80
15  36   94   60     41
16  87   38   56     93
17  91   14   90     57
18   0   21   22     13
19  34   79   87     68
20  50   54   32     10
21  12   23   37     47
22  29   64   73     92
23   9   74   92      7
24  38   23   52     17
25   1   26   10     83
26  16   31   62     40
27  34   78   99     28
28  43   30    1     67
29  89   81   54     39
30  26    5   11     20
31   6   58   63     26
32  66   58   23     23
33  96  100   95     71
34  74   87   30     69
35  91  100   95     48
36  55   74   54     78
37  26   82   89     23
38  75   33  100     99
39  86   52   29     49
40  83   13   29     33
41  67   95   82     67
42  19   92   15     10
43  58   95   89     70
44  16    2   50     40
45  42   79   73     94
46  89   98   56     95
47  68   67   79     10
48  16   21   45     19
49  30  100   62     29

In [18]:
x=data[['f1','f2','f3']]

In [20]:
y=df['label']

In [22]:
from sklearn.model_selection import train_test_split

In [24]:
 X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [27]:
X_train.shape

(33, 3)